### ISSUE TITLE
Width

### ISSUE THREAD

**Issue by Diego-Lopes-Ferreira** [Diego-Lopes-Ferreira/diego-frontend#2]
The scroll bar is on the div className="app" instead of being in the body. So the scroll bar for side scrolling was appearing...

**Comment by Diego-Lopes-Ferreira** [comment]
## Solved:

```css
/* instead of this */
.app {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;
}

/* do this */
.app {
  width: 100vw;
  display: flex;
  flex-direction: column;
}
```

The `100vh;` was making the scroll bar stay on the app div, instead of the window itself
